# Generated by Django 2.1.1 on 2018-09-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyWayPointsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('search_date', models.DateField(verbose_name='Date Searched')),
            ],
        ),
    ]
